### ISSUE TITLE
Break layout in desktop mode

### ISSUE THREAD

**Issue by kubil-ismail** [suprayogo/learn-react-fe#1]
if i open in laptop 13 & 14 inch your web show as well but if i open in monitor 27 inch your layout breaking. Please fix bg_yellow height dont use px instead using 100vh for dynamic height
![Screenshot (117)](https://github.com/suprayogo/Food-Recipe-FE/assets/49361887/7951501d-cbac-4813-a8d2-78ee67298738)

**Comment by suprayogo** [comment]
thanks for the comment I will fix it soon

**Comment by suprayogo** [comment]
[
![Captureas](https://github.com/suprayogo/Food-Recipe-FE/assets/126061696/2f2cec02-2782-4c7d-a08e-b2d7723d860c)
![Web capture_8-8-2023_44146_responsivedesignchecker com](https://github.com/suprayogo/Food-Recipe-FE/assets/126061696/4908cf24-18a4-4b29-98b6-63a372e5bd0b)
](url)

i have fixed the height in bg_yellow using 110vh

**Comment by kubil-ismail** [comment]
done
<img width="1680" alt="Screenshot 2023-08-10 at 01 11 01" src="https://github.com/suprayogo/Food-Recipe-Web/assets/49361887/5906eb23-1297-4c24-bc18-2f7804cd5dda">
